Repository 2025-K-PaaS-Team/cheap-bob, pull requests merged in 2025-08, with the labels that each got.

#7 fix: 로그인 Redirect를 프론트 개발 서버와 클라우드 서버 두 곳으로 수정
  backend/.env.example
  backend/app/api/v1/auth.py
  backend/app/config/settings.py
Labels: fix

#8 CORS 에러 해결
  backend/app/main.py
Labels: fix

#9 feat: Login auth 페이지 추가
  frontend/src/App.tsx
  frontend/src/components/home/LoginButton.tsx
  frontend/src/pages/Login/LoginSuccess.tsx
  frontend/src/pages/Login/index.ts
Labels: feat

#10 feat: 로그인 시 localStorage token 저장 로직 추가
  frontend/src/App.tsx
  frontend/src/pages/Home/Home.tsx
  frontend/src/pages/Login/Google.tsx
  frontend/src/pages/Login/Kakao.tsx
  frontend/src/pages/Login/LoginSuccess.tsx
  frontend/src/pages/Login/Naver.tsx
  frontend/src/pages/Login/index.ts
Labels: feat

#11 build: Vercel 404 에러 해결
  .github/PULL_REQUEST_TEMPLATE.md
  frontend/vercel.json
Labels: fix, build

#12 Cross Domain 토큰 이슈 해결
  backend/app/api/v1/auth.py
Labels: fix

#14 feat: Lab 페이지 구현
  frontend/.env
  frontend/src/App.tsx
  frontend/src/global.d.ts
  frontend/src/pages/Home/Home.tsx
  frontend/src/pages/Lab/Lab.tsx
  frontend/src/pages/Lab/Map.tsx
  frontend/src/pages/Lab/index.ts
Labels: feat

#16 backend 도커 path 수정 및 코드 리팩토링
  docker/backend/Dockerfile
  docker/docker-compose.yml
Labels: refactor

#17 누락된 리팩토링 코드 업로드
  backend/app/api/deps.py
  backend/app/api/v1/api.py
  backend/app/api/v1/auth.py
  backend/app/api/v1/payment.py
  backend/app/api/v1/search.py
  backend/app/config/oauth.py
  backend/app/core/portone.py
  backend/app/database/models/__init__.py
  backend/app/database/models/customer.py
  backend/app/database/models/seller.py
  backend/app/database/session.py
  backend/app/main.py
  backend/app/middleware/auth.py
  backend/app/repositories/base.py
  backend/app/repositories/customer.py
  backend/app/repositories/seller.py
  backend/app/services/auth/jwt.py
  backend/app/services/auth/oauth_service.py
  backend/app/services/oauth/base.py
  backend/app/services/oauth/factory.py
  backend/app/services/oauth/google.py
  backend/app/services/oauth/kakao.py
  backend/app/services/oauth/naver.py
  backend/app/services/payment.py
  backend/entrypoint.sh
Labels: refactor
